import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl'
import { notFound } from 'next/navigation'
import '@/utils/css/normalize.css'
import '@/utils/css/style.css'
import Navbar from '@/components/Navbar/Navbar'

const poppins = Poppins({ weight: ['300', '400', '500'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio Padermo',
  description: 'Generated by create next app',
}

export function generateStaticParams(){
  return [{locale:'en'},{locale:'es'}]
}

type Params = {
  locale:string
}

type ComponentProps={
  children: React.ReactNode,
  params: Params
}

export default async function RootLayout({children, params:{locale}}: ComponentProps) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default
  } catch (error) {
    notFound()
  }
  return (
    <html lang={locale}>
      <body className={poppins.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {/* <Navbar/> */}
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
